#remote_theme: just-the-docs/just-the-docs

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Council of Lórien
# description: Council of Lórien
# baseurl: "/just-the-docs" # the subpath of your site, e.g. /blog
# url: "https://counciloflorien.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.counciloflorien.com" # the base hostname & protocol for your site, e.g. http://example.com

permalink: pretty

exclude:
 # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
 # specific to the theme website:
   - bin/
   - lib/
   - "*.gemspec"
   - "*.gem"
   - LICENSE.txt
   - package.json
   - package-lock.json
   - Rakefile
   - README.md

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/counciloflorien.svg"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: false
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 4
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  # tokenizer_separator: /[\s/]+/
  tokenizer_separator: /[\s\-/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: false
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: true

# To disable support for mermaid diagrams (https://mermaid-js.github.io/mermaid/),
# comment out the `mermaid` and `version` keys below
# By default, consuming the theme as a gem leaves mermaid disabled; it is opt-in
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.6"
  # Put any additional configuration, such as setting the theme, in _includes/mermaid_config.js
  # See also docs/ui-components/code

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  #"Riddle":
  #  - "/riddle"
  #"About":
  #  - "/about"
  #"Just the Docs":
  #  - "//github.com/just-the-docs/just-the-docs"
  #"Contact":
  #  - "//mailto:counciloflorien@gmail.com"
  

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

# External navigation links
#nav_external_links:
  #- title: MECCG on Board Game Geek
    #url: https://boardgamegeek.com/boardgame/1915/middle-earth

# Footer content
# appears at the bottom of every page's main content

# Back to top link
#back_to_top: true
#back_to_top_text: "Back to top"

#footer_content: "&copy; Council of Lorien 2022"

# Footer last edited timestamp
#last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
#last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html



# Footer "Edit this page on GitHub" link text
# gh_edit_link: true # show or hide edit this page link
# gh_edit_link_text: "Edit this page on GitHub"
# gh_edit_repository: "https://github.com/just-the-docs/just-the-docs" # the github URL for your repo
# gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
# gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

callouts_level: quiet # quiet or loud, loud is night mode
callouts_opacity: 1.0
callouts:
  highlight:
    color: yellow
  Grey-md:
    color: grey-md
  Grey-dk:
    color: grey-dk
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    color: grey-md
  note-dk:
    color: grey-dk
  clarification:
    title: Clarification
    color: grey-md
  example:
    color: grey-dk
  exception:
    title: Exception
    color: grey-md
  suggestion:
    title: Suggestion
    color: grey-md
  metw:
    color: metw
  meul:
    color: meul
  metd:
    color: metd
  medm:
    color: medm
  mele:
    color: mele
  meas:
    color: meas
  mewh:
    color: mewh
  mech:
    color: mech
  meba:
    color: meba
  metw-title:
    title: The Wizards Limited
    color: metw
  meul-title:
    title: The Wizards Unlimited
    color: meul
  mele-title:
    title: The Lidless Eye
    color: mele
  mewh-title:
    title: The White Hand
    color: mewh
  meba-title:
    title: The Balrog
    color: meba
  lore:
    title: Lore
    color: yellow
  counsel:
    color: yellow
  tip:
    title: Tip
    color: grey-md
  hero-resource:
    color: hero-resource
  hero-resource-title:
    color: hero-resource-title
  hero-resource-text:
    color: hero-resource-text

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: G-VXF8SS6HFJ
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

plugins:
  - jekyll-seo-tag

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all
